/*#################################### Grupo SETGo #################################
Autor: Ing. Pedro Alan Sierra
Descripción: Service del Handler Opportunity_Handler_cls
------------------------------------- Log de cambios -------------------------------
Fecha		Versión		Autor							Descripción
----------	-------		----------------------------	-------------------------			
27/01/2018	1.0			Ing. Pedro Alan Sierra			Creación
###################################################################################*/
public with sharing class Opportunity_Service_cls{

	//Tiempo de ejecución: After Insert, After Update, After Delete
	//Descripción:
	public void Metodo(){
		
	}

}