/*#################################### Grupo SETGo #################################
Autor: Ing. Pedro Alan Sierra
Descripción: Clase de prueba del service: Opportunity_Handler_cls
------------------------------------- Log de cambios -------------------------------
Fecha		Versión		Autor							Descripción
----------	-------		----------------------------	-------------------------			
27/01/2018	1.0			Ing. Pedro Alan Sierra			Creación
###################################################################################*/
@isTest
public class Opportunity_Service_tst {

}